---
output:
  # pdf_document: 
  #   df_print: kable
  # html_document:
  #   df_print: kable
  word_document:
    reference_docx: ecology_doc.docx
    df_print: kable
csl: ecology.csl
bibliography: refs.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = T, results = T, message = F, warning = F, eval = T, fig.dim = c(4,4))
library(dplyr)
library(drake)
library(multipanelfigure)
library(ggplot2)
theme_set(theme_bw())

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analyses", "caches", "all_hasty_toy.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")


```
---
output:
  # word_document:
  #   reference_docx: different_gdoc.docx
  #   df_print: kable
  # html_document:
  #   df_print: kable
  pdf_document: 
    df_print: kable
csl: ecology.csl
bibliography: refs.bib
---
# Introduction

Understanding the interrelated dynamics of size- and -abundance based dimensions of biodiversity is key to understanding biodiversity change in the Anthropocene. Total abundance - i.e. the total number of individual organisms present in a system - and size-based currencies, such as the total biomass or total metabolic flux (“energy use”) of a system, are intertwined, but nonequivalent, measures of biological function. Abundance is more closely tied to species-level population dynamics, while size-based metrics more directly reflect assemblage-level resource use and contributions to materials fluxes at the broader ecosystem scale [@morlon2009; @dornelas2011; @white2007; @connolly2005]. While these currencies are naturally linked [@henderson2010; @morlon2009], changes in size composition can decouple the dynamics of one currency from another [@dornelas2011; @white2004; @white2007; @ernest2009; @yen2017]. This can mean that intuition from one currency may be misleading about others; a trend in numerical abundance might mask alternative dynamics occurring with respect to biomass or total energy use [@white2004]. Changes in size composition strong enough to decouple currencies may be symptomatic of important changes in ecosystem status- e.g. abundance-biomass comparison curves [@petchey2010]; size-biased extinctions [@young2016; @smith2018]. This underscores the need to understand how these dynamics are playing out in the Anthropocene [@fisher2010]. 

At the community scale, changes in the relationship between size and abundance can signal important shifts in community structure and functional composition. To the extent that size is a proxy for other functional traits, changes or consistency in the community-level size structure (individiual size distribution, ISD) over time may reflect processes related to niche structure [@white2007; @petchey2010]. Strong size shifts can decouple the relationship between abundance and biomass. In aquatic systems, such changes in the scaling between abundance and biomass often signal ecosystem degradation [@petchey2010; @kerr2001; @warwick1994]. Compensatory shifts in the size structure can buffer community function (in terms of biomass or energy use) against changes in abundance [@terry2015; @ernest2009; @white2004]. Or, consistency in the size structure may maintain the relationship between size- and -abundance based currencies, even as species composition, total abundance, and total biomass/total energy use fluctuate over time, which can reflect consistency in the niche structure over time [@holling1992]. 


It is important to improve our understanding of these dynamics for terrestrial animal communities in particular. In contrast to terrestrial trees and aquatic systems [@kerr2001; @white2007], how the relationship between size and abundance changes over time, and the consequences of these changes for ecosystem-level properties, remain relatively unknown for terrestrial animals (but see @white2004). Terrestrial animal communities exhibit size structure [@ernest2005; @thibault2011], and case studies have demonstrated that size shifts can decouple the dynamics of abundance, biomass, and energy use for terrestrial animals [@white2004; @yen2017], but do not always do so [@hernandez2011]. Establishing generalities in these dynamics is especially pertinent in the Anthropocene, as these communities are experiencing extensive and potentially size-structured change, with implications at community, ecosystem, and global scales [@young2016; @schmitz2018].

Macroecological-scale synthesis on the interrelated dynamics of the ISD, total abundance, and community function for terrestrial animals has been constrained by 1) a lack of community-level size and abundance timeseries data for these systems [@white2007; @thibault2011], and 2) appropriate statistical methods for relating change in the size structure to changes in abundance and function [@thibault2011; @yen2017]. In contrast to aquatic and forest systems, most long-term surveys of animal communities do not collect data on individuals' *sizes* across a full community (with the exception of small mammal studies, which have made major contributions to our understanding of the dynamics of size, abundance, and function for these systems; [@ernest2005; @white2004; @hernandez2011; @kelt2015]). Global, continental, or population-wide studies capture different phenomena [@white2007; @mcgill2015]. The ISDs for terrestrial animals, and specifically for determinate growing taxa (e.g. mammals, birds), are often complex, multimodal distributions strongly determined by community *species* composition [@holling1992; @ernest2005; @thibault2011; @yen2017] and less statistically tractable than the power-law ISDs found in aquatic and tree systems [@kerr2001; @white2007]. Quantifying change in the size structure, and relating this to change in community-wide abundance and function, is not as straightforward as computing and comparing slopes. As a result, we do not have a general understanding of either 1) how the size structures for these systems behave over time or 2) the extent to which changes in community size structure decouple the community-level dynamics of abundance, biomass, and energy use in these systems.

Here, we begin to address this gap by exploring how temporal changes in the size structure modulate the relationship between total abundance, energy, and biomass for communities of North American breeding birds. We used allometric scaling to estimate community size and abundance data for the North American Breeding Bird Survey, and evaluated how changes in total abundance, biomass, and energy use have co-varied from 1988-2018. Specifically, we examined: 1) How often do these currencies change together vs. have decoupled dynamics?; 2) What are the dominant directions and magnitudes of the overall change over time and degree of decoupling between the currencies?; 3) To what extent do changes in species composition and community size structure translate into decoupling in the temporal trends of different currencies at the community scale?



# Methods

## Bird abundance data

We used data from the Breeding Bird Survey [@pardieck2019] to evaluate trends in abundance, biomass, and energy use. The Breeding Bird Survey consists of roughly 40km-long survey routes distributed throughout the United States and Canada. Routes are surveyed annually during the breeding season (predominately May-June), via 50 3-minute point counts during which all birds seen or heard are identified to species [@pardieck2019]. Sampling began in 1966, and routes have been added over time to a current total of roughly 3000 routes (@pardieck2019) We explored trends in abundance, biomass, and energy use over the 30-year time period from 1989-2018. We selected these years to provide a temporal window sufficient to detect trends (@cusser2020), while allowing for a substantial number of routes. To avoid irregularities caused by missing time steps, we restricted the main analysis to routes that had been sampled in at least 27 of 30 years in this window (n = 739), and compared these results to a more strict selection of routes that were sampled in every year (n = 199). We take the route to be the "community" scale [@thibault2011]. We filtered the data to remove taxa that are poorly sampled through these methods, following @harris2018. We accessed the data, and performed this preliminary cleaning and filtering, using the R package `MATSS` [@ye2020]. 

##  Estimated size data

BBS contains abundances for all species along a route in each year, but does not include measurements of individual body size. We generated body size estimates for individual birds assuming that intraspecific size distributions are normally distributed around a species’ mean body size (following @thibault2011). Using records of species’ mean and standard deviation body sizes from @dunning2008, we drew individuals’ body sizes from the appropriate normal distributions. For species for which there was not a standard deviation recorded in @dunning2008 (185 species affected, of 421 total), we estimated the standard deviation using an allometric scaling relationship between mean and standard deviation in body mass constructed by fitting a linear model to the records in our dataset that did have mean and standard deviation measurements (resulting in the scaling relationship $log(variance) = -5.273 + (log(mass) * 1.995))$; model R2 .86; see also @thibault2011). For species with multiple records in @dunning2008, we used the mean mean and standard deviation body sizes across all records (averaging across sexes, subspecies, and records from different locations). We performed this averaging after estimating any missing standard deviation measurements. For each individual bird observed, we estimated metabolic rate as $10.5 * (mass ^.713)$ [@fristoe2015; @nagy2005; @mcnab2009]. For each route in a given year, we compute total energy use, total biomass, and total abundance by summing over all individuals observed on that route in that year. This method does not incorporate intraspecific variation in body size across geographies or over time [@dunning2008; @gardner2011]. However, it makes it possible to conduct macroecological studies of avian size distributions at a spatial and temporal scale that would otherwise be impossible [@thibault2011].

## Comparing abundance- and size- based currencies

Comparing trends across different currencies is a nontrivial statistical problem. Because different currencies vary widely in their units of measure (e.g. abundance in the hundreds of individuals; total biomass in the thousands of grams) and , it is challenging to interpret differences in magnitude of slope across different currencies. Transformation and scaling using common approaches (such as a square-root transformation, or rescaling each currency to a mean of 0 and a standard deviation of 1) destroys information about the degree of variability within each currency that is necessary in order to make comparisons *between* currencies for the same timeseries. 

Rather than attempting to compare slopes across currencies or to transform different currencies to a common scale, we used a simple null model to compare the observed dynamics for biomass and energy use to the dynamics that would occur in a scenario in which the species composition (and therefore, in this context, size structure) of the community was consistent throughout the timeseries, but in which total abundance varied over time consistent with the observed dynamics. For each route, we characterized the "observed" timeseries of total biomass and total energy use by simulating size measurements for all individuals observed in each time step and summing across individuals, using the method described above. We then simulated timeseries for "abundance-driven" dynamics of biomass and energy use incorporating observed changes in community-wide abundance over time, but under a scenario of consistent species (and therefore approximate size) composition over time. For each community, we characterized the timeseries-wide probability of an individual drawn at random from the community belonging to a particular species ($P(s_i)$) as each species' mean relative abundance taken across all timesteps: 

$P(s_i) = \frac{\sum_t^T{\frac{n_{i, t}}{N_t}}}{T}$

where $n_{i, t}$ is the abundance of species $i$ in timestep $t$, $N_t$ is the total abundance of all species in timestep $t$, and $T$ is the total number of timesteps. For each timestep $t$, we randomly assigned species' identities to the total number of individuals of all species observed in that time step ($N_t$) by drawing with replacement from a multinomial distribution with probabilities weighted according to $P(s)$ for all species. We then simulated body size measurements for individuals, and calculated total energy use and total biomass, following the same procedure as for the observed community. This characterizes the dynamics for size-based currencies expected if the species (and size) composition of the community does not change over time, but incorporating observed fluctuations in total abundance. We refer to these dynamics as "abundance-driven" dynamics. 

## Long-term trends

For each route, we evaluated the 30-year trend in biomass (or energy use) and compared this to the trend derived from the "abundance-driven" null model using generalized linear models with a Gamma family and log link (appropriate for strictly-positive response variables such as biomass or total metabolic flux). We fit four models to characterize 1) the trend in biomass (or energy use) over time and 2) whether this trend deviates from the trend expected given only changes in abundance:

1. `biomass ~ year * dynamics`, in which "dynamics" refers to being either the "observed" or "abundance-driven" (null model) dynamics. This model fits a slope and intercept for the observed trend in  biomass (or energy use) over time, and a separate slope and intercept for the trend drawn from the abundance-driven, or null model, dynamics.
2. `biomass ~ year + dynamics`. This model fits a separate intercept, but not slope, for the abundance-driven and observed dynamics. These models were never selected as the best-performing descriptions of community dynamics.
3. `biomass ~ year`. This model fits a temporal trend, but does not fit separate trends for the observed and abundance-driven dynamics.
4. `biomass ~ 1`. The intercept-only model describes no directional change over time for either the observed or abundance-driven dynamics. 

We selected the best-fitting model using AICc. In instances where multiple models had AICc scores within two AICc units of the best-fitting model, we selected the simplest model within two units of the best score.

For each route's selected model, we extracted the predicted values for the first (usually 1988) and last (usually 2018) year sampled, for both the observed and null trajectories. We calculated the magnitude of change over time as the ratio of the last (2018) to the first (1988) value, and characterized the direction of the long-term trend as increasing if this ratio was greater than one, and decreasing if it was less than one. 

## Relating change in community structure to decoupling between abundance and size-based dynamics

Community dissimilarity metrics are most readily interpretable when making pairwise comparisons (as opposed to repeated comparsions over a timeseries). We compared the first and last five-year intervals in each timeseries, resulting in a "begin" and "end" comparison separated by a relatively consistent window of time across routes (usually 19-20 years). The use of five-year periods corrects for sampling effects (@white2004a), smooths out interannual variability, and, by including a relatively large proportion (1/3) of the total timeseries, partially mitigates the impact of scenarios where the start and end values do not align with the long-term trend. 

We calculated three metrics to explore how changes in community composition and size structure translate into decoupling between abundance-driven and observed dynamics for biomass and energy use.  First, we evaluated the change in average community-wide body size, calculated as the log ratio of mean body size in the last five years relative to the mean body size in the first five years:

$\ln(\frac{\bar{m}_{last5}}{\bar{m}_{first5}})$

where $\bar{m}_{first5}$ and $\bar{m}_{last5}$ is the mean body size of all individuals observed in the first and last 5 years, respectively. Large changes in average body size are, by definition, expected to translate into decoupling between observed and abundance-driven dynamics.

Second, we calculated measures of turnover in the size structure and in species composition. We calculated turnover in the ISD using a measure inspired by an overlap measure that has previously been applied to species body size distributions in mammalian communities (@read2018). We characterized each "begin" or "end" ISD as a smooth probability density function by fitting a Gaussian mixture model (with up to 15 Gaussians; following @thibault2011) to the raw distribution of body masses, and extracting the fitted probability density at 1000 evaluation points corresponding to body masses extending beyond the range of body masses present in this dataset (specifically, from 0 to 15 kilograms; mean body masses in this dataset range from 2.65 grams, for the Calliope hummingbird *Selasphorus calliope*, to 8.45 kg, for the California condor *Gymnogyps californianus*). We rescaled each density function such that the total probability density summed to 1. To calculate the degree of turnover between two ISDs, we calculated the area of overlap between the two density smooths as $\sum{\min(density1_i, density2_i)}$ where $density1_i$ is the probability density from the density smooth for the first ISD at evaluation point $i$, and $density2_i$ is the probability density from the density smooth for the second ISD at that evaluation point. We subtracted this quantity from 1 to obtain a measure of turnover between two ISDs.


To evaluate turnover in species composition between the five-year time periods, we calculated Bray-Curtis dissimilarity between the two communities using the R package `vegan` [@pinheiro2020]. 

We tested whether routes whose dynamics were best-described using different syndromes of change (no trend, couple trends, or decoupled trends) differed in 1) the magnitude of change in mean body size; 2) turnover in the ISD over time; or 3) species compositional turnover over time. For change in mean body size, we fit an ordinary linear model of the form `abs(log ratio (mean body size)) ~ best fitting model type`. We used the absolute log ratio so as to focus on the magnitude, rather than the direction, of change in body size (see also @supp2014a for the use of the absolute log ratio to examine the magnitudes of differences between values). We compared this model to an intercept-only null model of the form `abs(log ratio(mean body size)) ~ 1`. Because our metrics for turnover in the ISD and species composition are bounded from 0-1, we analyzed these metrics using binomial generalized linear models of the form `ISD turnover ~ best fitting model type` and `dissimilarity ~ best fitting model type`, and again compared these models to intercept-only null models. In instances where the model fit with `best fitting model type` outperformed the intercept-only model, we calculated model estimates and contrasts using the R package `emmeans` [@lenth2021]. 





# Results

This analysis revealed qualitatively different continent-level patterns in the long-term trends for biomass, energy use, and total abundance (Figure 2). Of the 739 routes in this analysis, approximately 70% (500/739 for biomass, and 509/739 for energy use) were best-described using a model incorporating a temporal trend in abundance and/or biomass or energy use (Table 1). Trends driven by abundance, as reflected by the dynamics of a simple null model, were strongly dominated by declines (335 decreases and 165 increases for abundance-driven dynamics in biomass, and 355 decreases and 154 increases for abundance-driven dynamics in energy use; Figure 2; Table 2). In contrast, for biomass, the long-term temporal trends were evenly balanced between increases and decreases (256 decreasing trends, and 244 increasing trends; Figure 2;  Table 2). For energy use, there was a greater representation of decreasing trends than for biomass, but still less so than for strictly abundance-driven dynamics (329 decreasing trends and 180 increasing trends;  Figure 2; Table 2). 

These divergent aggregate outcomes in abundance, energy use, and especially biomass occurred due to decoupling in the long-term trends for these different currencies. For a substantial minority of routes (20% of all routes for biomass, and 7% of all routes for energy use), the best-fitting model fit a different long-term trend for biomass or energy use than for the "null", abundance-driven, trend (Table 1). When this decoupling occurred, it was dominated by scenarios in which the slope for abundance-driven dynamics was more negative than that for biomass or energy use (Figure 3). 

Decoupling between the long-term trajectories of abundance and energy use or biomass is, by definition, indicative of some degree of change in the ISD over time. Routes whose dynamics were best-described as decoupled trends over time had a higher absolute log ratio of mean mass (i.e. greater magnitude of change, either increasing or decreasing, in mean mass over time) than routes with coupled or no trends (Tables 3-5). However, there was not a detectable difference in the degree of temporal turnover in the ISD overall (Table 6), or in species composition (Table 7), compared between routes that exhibited different dynamics (i.e. no linear temporal trend, a consistent temporal trend for abundance and biomass or energy use, or differing trends for abundance and biomass or energy use) .





# Discussion

## Abundance, biomass, and energy use are nonequivalent currencies

Simultaneously examining multiple currencies of community-level abundance revealed qualitatively different continent-wide patterns in the long-term trends for abundance in terms of individuals, biomass, and energy use. While long-term trends in individual abundance were dominated by decreases, long-term trends in biomass were evenly split between increases and decreases, and trends in energy use were again dominated by declines (Figure 2). These different currencies, though intrinsically linked,  describe nonequivalent dimensions of community function and reflect different classes of structuring processes [@morlon2009]. Abundance, in terms of individuals, is most directly linked to species-level population dynamics of the type often considered in classic, particularly theoretical, approaches to studying competition, compensation, and coexistence  (e.g. @hubbell2001; @chesson2000). Biomass most directly reflects the productivity of a community and its potential contributions to materials fluxes in the broader ecosystem context, whereas energy use - by taking into account the metabolic inefficiencies of organisms of different body size  - characterizes the total *resource use* of a community and may come the closest to capturing signals of bottom-up constraints, "Red Queen" effects, or zero-sum competitive dynamics [@morlon2009; @ernest2009; @white2004; @vanvalen1973; @ernest2008]. Our results underscore that, while trends in abundance, biomass, and energy use naturally co-vary to some extent, shifts in the  community size structure can and do produce qualitatively different trends for these different currencies. These may reflect contrasting long-term changes in different types of community processes - for example, shifts in habitat structure that affect the optimal body sizes for organisms in a system, but do not result in overall changes in resource availability (e.g. @white2004). Moreover, extrapolating the long-term trend from one currency to another may elide underlying changes in the community that complicate these dynamics. To appropriately monitor different dimensions of biodiversity change, it is therefore important to focus on the specific currency most closely aligned with the types of processes and dynamics - e.g. population fluctuations, resource limitation, or materials fluxes - of interest in a particular context. 

##  For North American breeding birds, biomass has declined less than abundance or energy use

For communities with a decoupling in the long-term trends of biomass, energy use, and abundance, this decoupling is indicative of a directional shift in the size structure of the community. For the communities of breeding birds across North America considered here, the long-term trends in total biomass are often less negative than trends in total abundance or total energy use (Figure 3). This consistent (but not ubiquitous) signal corresponds to community-level increases in average body size that partially or completely buffer changes in total against declines in abundance. This contrasts with general, global concerns that larger-bodied species are more vulnerable to extinction and population declines than smaller ones [@smith2018; @young2016; @dirzo2014; @ref]. However, it is consistent with previous findings from the Breeding Bird Survey [@schipper2016]. Increases in body size may reflect forests in recovery across North America over this timespan [@schipper2016], or the contributions of relatively few, large-bodied species that may in fact benefit from recent ecological changes [@ref?]. The long-term trends for communities of different taxonomic groups, geographies, or temporal spans may show different effects related to different facets of global change and biodiversity responses. 

We note that these increases in body size do not generally appear great enough to decouple the long-term trends in *energy use* from total abundance (Figure 3). Energy use scales nonlinearly with body size with an exponent less than 1, which means that community-wide increases in mean body size result in smaller increases in total energy use than in total biomass. 


## Complex relationships between compositional change and community-level properties

The decoupling between the long-term trends for biomass, abundance, and energy use demonstrated in many of the communities studied here is symptomatic of a directional shift in the size structure - in these instances, generally favoring larger bodied species. However, examining the community-wide dynamics of turnover in species composition and the overall size structure reveals that the relationship between changes in community structure and changes in the scaling between different currencies of community-wide abundance is considerably more nuanced than simple directional shifts in mean size.  Routes that exhibit a statistically detectable decoupling between total biomass and total abundance show large changes in average body size compared to routes for which biomass and abundance either change more nearly in concert with each other or do not show temporal trends (Figure 4). This aligns naturally with mathematical intuition given the intrinsic relationship between average body size, total abundance, and total biomass. However, these routes are *not* extraordinary in terms of their overall degree of temporal turnover in either the size structure or in species composition. Rather, the levels of turnover in overall community structure are comparable between routes that show decoupling between abundance and biomass, statistically indistinguishable trends, or no temporal trends in either currency (Figure 4). 

For many communities, therefore, there has been appreciable change in the species and size composition that simply does not manifest in a shift in the overall community-wide mean body size or mean metabolic rate sufficient to decouple the dynamics of biomass, abundance, and energy use. These changes may signal changes in functional composition equally important as the ones that manifest in directional shifts in community-wide average body size. For the complex, multimodal size distributions that are the norm for avian communities [@thibault2011], changes in the number and position of modes may be as important as changes in higher-level statistical moments such as the overall mean. At present, the field lacks the statistical tools and conceptual frameworks to quantify and interpret these nuanced changes, especially at the macroecological scale of the current study [@thibault2011; @yen2017]. However, this is an excellent opportunity for more system-specific work, informed by natural history knowledge and process-driven expectation, to characterize more nuanced changes in the size structure of specific communities and identify the underlying drivers of these changes. To facilitate these efforts in the context of the Breeding Bird Survey, the R package we have developed to characterize the individual size distributions for avian communities based on species' identities and/or mean body sizes is freely available for re-use and wider applications (*cite dissertation version here - I am working on a more general-use version to publish more widely, e.g. in JOSS, but not by March!*). 


# Conclusion

This analysis demonstrates the current power, and limitations, of a data-driven macroecological perspective on the interrelated dynamics of community size structure and different dimensions of community-wide abundance for terrestrial animal communities. For breeding bird communities across North America, we find that changes in species and size composition produce qualitatively different aggregate patterns in the long-term trends of abundance, biomass, and energy use, highlighting the nuanced relationship between these related, but decidedly nonequivalent, currencies and reflecting widespread changes in community size structure that may signal substantive changes in functional composition. Simultaneously, the complex relationship between turnover in community species and size composition, and the scaling between different currencies of community-level abundance, highlights opportunities for synergies between recent computational and statistical advances, case studies grounded in empiricism and natural history, and future macroecological-scale synthesis to realize the full potential of this conceptual space. 

\newpage
# References
