---
output:
  # word_document:
  #   reference_docx: default_gdoc.docx
  #   df_print: kable
  # html_document:
  #   df_print: kable
  pdf_document: 
    df_print: kable
csl: ecology.csl
bibliography: refs.bib
---


# Discussion

## Biological interpretation of results

While changes in size-based currencies usually scale with abundance, in a substantial minority of instances they do not. Meaning, there has been directional shift in the size structure that changes the outcome for function vs abundance. 

This means we should extrapolate from "abundance" to "function" with some care. 

When these strong size shifts occur, it is also a prompt to dig deeper into what's going on in that system. 

When they diverge, it is usually in the direction of less-negative-change. Because abundance is usually decreasing, this is generally partially offsetting the decline in energy use/biomass that would be expected just given abundance. This contrasts with general in-the-ether concerns about size-biased declines disproportionately affecting large species. However, the increase in body size is consistent with other observations specific to BBS, possibly reflecting forests in recovery across North America. 

## Statistical considerations

An absence of a trend does not imply an absence of change. An absence of an interaction does not imply an absence of decoupling.

Both of these phenomena may be better captured through nonlinear dynamics. GAMs are a path forward here (BOX), but are challenging to interpret at scale.

## The argument for this contribution, and paths forward

I've done the best I can.

Going forward, I suggest using GAMs; focusing on specific routes; engaging deeply with processes that lead to change propagating across scale (from the level of species --> size --> mean size --> trajectories). Available methods do not yet permit strong inference about smaller-scale processes or nuanced dynamics at scale. 

\newpage
# References
