---
output:
  # word_document:
  #   reference_docx: default_gdoc.docx
  #   df_print: kable
  # html_document:
  #   df_print: kable
  pdf_document: 
    df_print: kable
csl: ecology.csl
bibliography: refs.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, include = T, results = T, message = F, warning = F, eval = T, fig.dim = c(3.5, 2))
library(dplyr)
library(drake)
library(multipanelfigure)
library(ggplot2)
theme_set(theme_bw())

## Set up the cache and config
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("analyses", "caches", "all_hasty_toy.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)
cache$del(key = "lock", namespace = "session")


loadd(all_preds, cache=cache)
loadd(all_aics, cache=cache)

winning_aics <- all_aics %>%
  filter(model_family == "Gamma") %>%
  group_by(matssname, model_family) %>%
  mutate(minAICc = min(model_AICc)) %>%
  mutate(deltaAICc = minAICc - model_AICc)  %>%
  mutate(exp_deltas = exp(.5 * deltaAICc)) %>%
  mutate(denom = sum(exp_deltas)) %>%
  mutate(aicc_wt = exp_deltas/ denom) %>%
  arrange(desc(aicc_wt)) %>%
  mutate(rank =row_number()) %>%
  ungroup() %>%
  arrange(matssname, model_family, rank)

delta_2 <- winning_aics %>% filter(deltaAICc > -2) %>%
  filter(model_family == "Gamma") %>%
  group_by(matssname, model_family) %>%
  arrange(modelcomplexity) %>%
  mutate(rank = row_number()) %>%
  filter(rank == 1) %>%
  ungroup()


winning_fits <- delta_2 %>%
  left_join(all_preds) 
```

# Results

## Model outcomes

Overall proportion of routes with winning models:

```{r, results =T}

winning_fits %>% group_by(model_family, model_formula) %>% tally() %>%
  mutate(prop = n / sum(n))

```

Of models with slope term, the proportion for which abundance and biomass are increasing:

```{r}
slope_winning_fits <- winning_fits %>%
  filter(modelcomplexity > 1)

interaction_winning_fits <- winning_fits %>%
  filter(modelcomplexity > 2)

slope_winning_fits %>%
  mutate(abundance_increasing = ratio_sim > 1) %>%
  group_by(abundance_increasing) %>%
  tally() %>%
  mutate(prop = n / sum(n))


slope_winning_fits %>%
  mutate(biomass_increasing = ratio_real > 1) %>%
  group_by(biomass_increasing) %>%
  tally() %>%
  mutate(prop = n / sum(n))
```


Restricted to models with an *interaction*:

```{r}
interaction_winning_fits %>%
  mutate(abundance_increasing = ratio_sim > 1) %>%
  group_by(abundance_increasing) %>%
  tally() %>%
  mutate(prop = n / sum(n))


interaction_winning_fits %>%
  mutate(biomass_increasing = ratio_real > 1) %>%
  group_by(biomass_increasing) %>%
  tally() %>%
  mutate(prop = n / sum(n))

```

## Direction and magnitude of slopes

```{r}
ggplot(slope_winning_fits, aes(ratio_sim)) + geom_histogram() + scale_x_log10() + geom_vline(xintercept = 1) + ggtitle("Abundance-driven (null model) slope")


ggplot(slope_winning_fits, aes(ratio_real)) + geom_histogram() + scale_x_log10() + geom_vline(xintercept = 1) + ggtitle("Observed slope")

```

## Direction of decoupling

```{r, fig.dim= c(4,4)}

interaction_all_fits <- all_preds %>% group_by_all() %>% filter( grepl( "* source",model_formula), model_family == "Gamma") %>% mutate(plus = substr(model_formula, 12,12) == "+") %>% filter(!plus) %>% ungroup() %>%
  left_join(select(winning_fits, matssname, model_formula) %>% rename(winning_formula = model_formula))

ggplot(interaction_all_fits, aes(ratio_sim, ratio_real)) + geom_point(alpha = .2) + geom_point(data = filter(interaction_all_fits, winning_formula != "1"), aes(color = winning_formula), alpha = .5) + scale_y_log10() + scale_x_log10() + scale_color_viridis_d(end = .8) + theme(legend.position = "bottom") + geom_abline(intercept = 0, slope = 1) + geom_vline(xintercept = 1) + geom_hline(yintercept = 1)
 
```

## CV of timeseries

## CorCoef of observed to null

##
\newpage
# References
