---
output:
  # word_document:
  #   reference_docx: different_gdoc.docx
  #   df_print: kable
  # html_document:
  #   df_print: kable
  pdf_document: 
    df_print: kable
csl: ecology.csl
bibliography: refs.bib
---
# Introduction

Understanding the interrelated dynamics of size- and -abundance based dimensions of biodiversity is key to understanding biodiversity change in the Anthropocene. Total abundance - i.e. the total number of individual organisms present in a system - and size-based currencies, such as the total biomass or total metabolic flux (“energy use”) of a system, are intertwined, but nonequivalent, measures of biological function. Abundance is more closely tied to species-level population dynamics, while size-based metrics more directly reflect assemblage-level resource use and contributions to materials fluxes at the broader ecosystem scale [@morlon2009; @dornelas2011; @white2007; @connolly2005]. While these currencies are naturally linked [@henderson2010; @morlon2009], changes in size composition can decouple the dynamics of one currency from another [@dornelas2011; @white2004; @white2007; @ernest2009; @yen2017]. This can mean that intuition from one currency may be misleading about others; a trend in numerical abundance might mask alternative dynamics occurring with respect to biomass or total energy use [@white2004]. Changes in size composition strong enough to decouple currencies may be symptomatic of important changes in ecosystem status- e.g. abundance-biomass comparison curves [@petchey2010]; size-biased extinctions [@young2016; @smith2018]. This underscores the need to understand how these dynamics are playing out in the Anthropocene [@fisher2010]. 


At the community scale, changes in the relationship between size and abundance can signal important shifts in community structure and functional composition. To the extent that size is a proxy for other functional traits, changes or consistency in the community-level size structure (individiual size distribution, ISD) over time may reflect processes related to niche structure [@white2007; @petchey2010]. Strong size shifts can decouple the relationship between abundance and biomass. In aquatic systems, such changes in the scaling between abundance and biomass often signal ecosystem degradation [@petchey2010; @kerr2001; @warwick1994]. Compensatory shifts in the size structure can buffer community function (in terms of biomass or energy use) against changes in abundance [@terry2015; @ernest2009; @white2004]. Or, consistency in the size structure may maintain the relationship between size- and -abundance based currencies, even as species composition, total abundance, and total biomass/total energy use fluctuate over time, which can reflect consistency in the niche structure over time [@holling1992]. 


It is important to improve our understanding of these dynamics for terrestrial animal communities in particular. In contrast to terrestrial trees and aquatic systems [@kerr2001; @white2007], how the relationship between size and abundance changes over time, and the consequences of these changes for ecosystem-level properties, remain relatively unknown for terrestrial animals (but see @white2004). Terrestrial animal communities exhibit size structure [@ernest2005; @thibault2011], and case studies have demonstrated that size shifts can decouple the dynamics of abundance, biomass, and energy use for terrestrial animals [@white2004; @yen2017], but do not always do so [@hernandez2011]. Establishing generalities in these dynamics is especially pertinent in the Anthropocene, as these communities are experiencing extensive and potentially size-structured change, with implications at community, ecosystem, and global scales [@young2016; @schmitz2018].

Macroecological-scale synthesis on the interrelated dynamics of the ISD, total abundance, and community function for terrestrial animals has been constrained by 1) a lack of community-level size and abundance timeseries data for these systems [@white2007; @thibault2011], and 2) appropriate statistical methods for relating change in the size structure to changes in abundance and function [@thibault2011; @yen2017]. In contrast to aquatic and forest systems, most long-term surveys of animal communities do not collect data on individuals' *sizes* across a full community (with the exception of small mammal studies, which have made major contributions to our understanding of the dynamics of size, abundance, and function for these systems; [@ernest2005; @white2004; @hernandez2011; @kelt2015]). Global, continental, or population-wide studies capture different phenomena [@white2007; @mcgill2015]. The ISDs for terrestrial animals, and specifically for determinate growing taxa (e.g. mammals, birds), are often complex, multimodal distributions strongly determined by community *species* composition [@holling1992; @ernest2005; @thibault2011; @yen2017] and less statistically tractable than the power-law ISDs found in aquatic and tree systems [@kerr2001; @white2007]. Quantifying change in the size structure, and relating this to change in community-wide abundance and function, is not as straightforward as computing and comparing slopes. As a result, we do not have a general understanding of either 1) how the size structures for these systems behave over time or 2) the extent to which changes in community size structure decouple the community-level dynamics of abundance, biomass, and energy use in these systems.


Here, we begin to address this gap by exploring how temporal changes in the size structure modulate the relationship between total abundance, energy, and biomass for communities of North American breeding birds. We used allometric scaling to estimate community size and abundance data for the North American Breeding Bird Survey, and evaluated how changes in total abundance, biomass, and energy use have co-varied from 1988-2018. Specifically, we examined: 1) How often do these currencies change together vs. have decoupled dynamics?; 2) What are the dominant directions and magnitudes of the overall change over time and degree of decoupling between the currencies?; 3) To what extent do changes in species composition and community size structure translate into decoupling in the temporal trends of different currencies at the community scale?

\newpage
# References
