---
output:
  # word_document:
  #   reference_docx: default_gdoc.docx
  #   df_print: kable
  # html_document:
  #   df_print: kable
  pdf_document: 
    df_print: kable
csl: ecology.csl
bibliography: refs.bib
---

# Results

This analysis revealed qualitatively different continent-level patterns in the long-term trends for biomass, energy use, and total abundance (Figure 2). Of the 739 routes in this analysis, approximately 70% (500/739 for biomass, and 509/739 for energy use) were best-described using a model incorporating a temporal trend in abundance and/or biomass or energy use (Table 1). Trends driven by abundance, as reflected by the dynamics of a simple null model, were strongly dominated by declines (335 decreases and 165 increases for abundance-driven dynamics in biomass, and 355 decreases and 154 increases for abundance-driven dynamics in energy use; Figure 2; Table 2). In contrast, for biomass, the long-term temporal trends were evenly balanced between increases and decreases (256 decreasing trends, and 244 increasing trends; Figure 2;  Table 2). For energy use, there was a greater representation of decreasing trends than for biomass, but still less so than for strictly abundance-driven dynamics (329 decreasing trends and 180 increasing trends;  Figure 2; Table 2). 

These divergent aggregate outcomes in abundance, energy use, and especially biomass occurred due to decoupling in the long-term trends for these different currencies. For a substantial minority of routes (20% of all routes for biomass, and 7% of all routes for energy use), the best-fitting model fit a different long-term trend for biomass or energy use than for the "null", abundance-driven, trend (Table 1). When this decoupling occurred, it was dominated by scenarios in which the slope for abundance-driven dynamics was more negative than that for biomass or energy use (Figure 3). 

Decoupling between the long-term trajectories of abundance and energy use or biomass is, by definition, indicative of some degree of change in the ISD over time. Routes whose dynamics were best-described as decoupled trends over time had a higher absolute log ratio of mean mass (i.e. greater magnitude of change, either increasing or decreasing, in mean mass over time) than routes with coupled or no trends (Tables 3-5). However, there was not a detectable difference in the degree of temporal turnover in the ISD overall (Table 6), or in species composition (Table 7), compared between routes that exhibited different dynamics (i.e. no linear temporal trend, a consistent temporal trend for abundance and biomass or energy use, or differing trends for abundance and biomass or energy use) .


\newpage
# References
